language: php

php:
  - 5.5
  - 5.6

script:
  - ./vendor/bin/phpunit

notifications:
  webhooks:
    - https://idobata.io/hook/734651d8-05c0-403f-a385-c647960a2767
  hipchat:
    rooms:
      secure: l3Eqsq6idQLE1Mh9PVBer9ZmoevskL4Qvr5tMuJi3Nqq+48CgwcOcZqp3tQZdULxeBen1aHAfoMARzQLCf7GkHFN62qVfEaSy9mJJkvXQ3S3/LfJdgm7saJ1gtpLyHQbAka9QPrZP6hd8gQEryCyegZyxbGRGBkMnaJhybNPIKw=