#!/usr/bin/env php
<?php
$autoloaders = [
    __DIR__ . '/../../autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/vendor/autoload.php'
];

foreach ($autoloaders as $file) {
    if (file_exists($file)) {
        require_once $file;
        break;
    }
}

// token from args
if ($argc < 2) {
    die(sprintf('Usage: %s TOKEN' . PHP_EOL, $argv[0]));
}
$token = $argv[1];

$client = new Shin1x1\LoaderIo\Client($token);

$loader = new Shin1x1\LoaderIo\TestLoader($client);
$results = $loader->load()->run();

echo (new \Shin1x1\LoaderIo\ResultRender($results))->render();
